name: syncer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bonsoir: ^5.1.9
  windows_network_adapter_info: ^0.0.1
  intl: ^0.19.0
  socket_io: ^1.0.1
  socket_io_client: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
